all:
	gcc -o ./HW7_stat ./HW7_stat.c
	gcc -o ./HW7_listfiles ./HW7_listfiles.c
	gcc -o ./HW7_tail ./HW7_tail.c
	gcc -o ./HW7_rs ./HW7_rs.c

clean:
	rm -f ./HW7_stat
	rm -f ./HW7_listfiles
	rm -f ./HW7_tail
	rm -f ./HW7_rs
	clear