CC 		= 	g++
CFLAG 	= 	-O2
CFLAG	+=	-Wall -Wextra

all:
	$(CC) $(FLAG) -o hostinfo hostinfo.c
	$(CC) $(FLAG) -o mydate mydate.c
	$(CC) $(FLAG) -o printdir printdir.c
	$(CC) $(FLAG) -o mycat mycat.c
	$(CC) $(FLAG) -o pipe_ls pipe_ls.c

clean:
	rm hostinfo mydate printdir mycat pipe_ls
